### ISSUE TITLE
不能直接发布release吗

### ISSUE THREAD

**Issue by wajika** [fawdhsun/harbor-auto-pruning#1]
这个jar包如何使用？ 
harbor的账号和密码房哪里？

**Comment by wajika** [comment]
Exception: 

org.springframework.web.client.UnknownContentTypeException: Could not extract response: no suitable HttpMessageConverter found for response type [java.util.List<com.faw.harbor.dtos.HarborProject>] and content type [text/html]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:126)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1034)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1017)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:630)
	at com.faw.harbor.service.impl.HarborRequestServiceImpl.queryProjects(HarborRequestServiceImpl.java:105)
	at com.faw.harbor.jobs.HarborPrunningJob.executeImageTagPruning(HarborPrunningJob.java:38)
	at com.faw.harbor.jobs.HarborPrunningJob.executeInternal(HarborPrunningJob.java:33)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

2021-03-14 15:31:42.710 [quartzScheduler_Worker-1] ERROR org.quartz.core.JobRunShell - Job DEFAULT.6da64b5bd2ee-d5b2e8f9-bc1c-45f2-b622-453a1229b287 threw an unhandled Exception: 
org.springframework.web.client.UnknownContentTypeException: Could not extract response: no suitable HttpMessageConverter found for response type [java.util.List<com.faw.harbor.dtos.HarborProject>] and content type [text/html]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:126)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1034)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1017)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:630)
	at com.faw.harbor.service.impl.HarborRequestServiceImpl.queryProjects(HarborRequestServiceImpl.java:105)
	at com.faw.harbor.jobs.HarborPrunningJob.executeImageTagPruning(HarborPrunningJob.java:38)
	at com.faw.harbor.jobs.HarborPrunningJob.executeInternal(HarborPrunningJob.java:33)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2021-03-14 15:31:42.712 ERROR 1674 --- [eduler_Worker-1] org.quartz.core.ErrorLogger              : Job (DEFAULT.6da64b5bd2ee-d5b2e8f9-bc1c-45f2-b622-453a1229b287 threw an exception.

org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.web.client.UnknownContentTypeException: Could not extract response: no suitable HttpMessageConverter found for response type [java.util.List<com.faw.harbor.dtos.HarborProject>] and content type [text/html]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:126)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1034)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1017)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:630)
	at com.faw.harbor.service.impl.HarborRequestServiceImpl.queryProjects(HarborRequestServiceImpl.java:105)
	at com.faw.harbor.jobs.HarborPrunningJob.executeImageTagPruning(HarborPrunningJob.java:38)
	at com.faw.harbor.jobs.HarborPrunningJob.executeInternal(HarborPrunningJob.java:33)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted

2021-03-14 15:31:42.712 [quartzScheduler_Worker-1] ERROR org.quartz.core.ErrorLogger - Job (DEFAULT.6da64b5bd2ee-d5b2e8f9-bc1c-45f2-b622-453a1229b287 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.web.client.UnknownContentTypeException: Could not extract response: no suitable HttpMessageConverter found for response type [java.util.List<com.faw.harbor.dtos.HarborProject>] and content type [text/html]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:126)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1034)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1017)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:630)
	at com.faw.harbor.service.impl.HarborRequestServiceImpl.queryProjects(HarborRequestServiceImpl.java:105)
	at com.faw.harbor.jobs.HarborPrunningJob.executeImageTagPruning(HarborPrunningJob.java:38)
	at com.faw.harbor.jobs.HarborPrunningJob.executeInternal(HarborPrunningJob.java:33)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
